// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://gfatujwalsusandoiyze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmYXR1andhbHN1c2FuZG9peXplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMxNjI5NjksImV4cCI6MjA3ODczODk2OX0.qE3p5N8repLT0hKm8MchF_cF9IhqD-ehjACW2L-isMU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);